### PR TITLE
Print Hello

### PR DESCRIPTION
**Pull request by mfellner**
The script should print "Hello, World!"

### CODE REVIEW

**Comment by mfellner** [comment]
I totally approve this pull request!

**Comment by mfellner** [comment]
Test!

**Comment by mfellner** [comment]
FOOOBARR!!!!

**Comment by prayerslayer** [comment]
- [ ] da fehlt was
- [ ] und da auch

**Comment by prayerslayer** [comment]
:+1:

**Comment by msvivienleung** [comment]
I approve :ok_woman:

**Pull request merged**
